#!/bin/bash
# handlebars_launch.sh — schd-facing launcher for Handlebars.app (generated by wrap-in-app).
# The app holds the TCC grant; this shim restores the poke-on-stdout convention the app
# swallows: print only NEW non-marker log lines from this run. LOG: /Users/jonathan/svnCheckouts/js-db-ad-astra/tools/handlebars/handlebars.log
APP="$(cd "$(dirname "$0")" && pwd)/Handlebars.app"
LOG="/Users/jonathan/svnCheckouts/js-db-ad-astra/tools/handlebars/handlebars.log"
before=0
[ -f "$LOG" ] && before=$(wc -l < "$LOG")
open -g -W -a "$APP" || { echo "Handlebars: FAILED to launch $APP"; exit 1; }
tail -n +$((before + 1)) "$LOG" | grep -v '^=== run '
exit 0
