#!/bin/bash
# xcodemcpfront_launch.sh — schd-facing launcher for XcodeMCPFront.app (generated by wrap-in-app).
# The app holds the TCC grant; this shim restores the poke-on-stdout convention the app
# swallows: print only NEW non-marker log lines from this run. LOG: /Users/jonathan/.xcode-mcp-front/daemon.log
APP="$(cd "$(dirname "$0")" && pwd)/XcodeMCPFront.app"
LOG="/Users/jonathan/.xcode-mcp-front/daemon.log"
before=0
[ -f "$LOG" ] && before=$(wc -l < "$LOG")
open -g -W -a "$APP" || { echo "XcodeMCPFront: FAILED to launch $APP"; exit 1; }
tail -n +$((before + 1)) "$LOG" | grep -v '^=== run '
exit 0
